
---
  - name: ensure httpd installed
    package:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: ensure httpd enabled
    service:
      name: httpd
      enabled: yes 
    when: ansible_distribution == "CentOS"

  - name: ensure httpd started
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"

  - name: ensure apache installed
    package:
      name: apache2
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache enabled
    service:
      name: apache2
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: ensure apache started
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"
...
