---
# handlers file for web-role
- name: Restarting the httpd
  service:
     name: httpd
     state: restarted

- name: Restarting the apache
  service:
     name: apache2
     state: restarted
...

